language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- chmod 777 ./tools/install-unity.sh
- ./tools/install-unity.sh
script:
- cd tools
- chmod 777 ./buildOSX.sh
- ./buildOSX.sh
- chmod 777 ./buildWIN.sh
- ./buildWIN.sh
deploy:
  provider: releases
  api_key:
    secure: 2uVqFpJsiqOHU7XRxN9oztmf3lC30XnVr/wKcN9mnpjwm4pROkWnz/HabbLN0arIDsUYOn1UiCqO10zOef/NZPA2hl0K9qoA28+sADczafTBx+Uamknq6Xt0HkQEPljfiIvS3RyYEHuf5m1DONlW88NiIj9wci2T3JnGVJwmA2KHxGGV+804WUE5dAgzndXXVb3wp86wVNBt2uv4NjBVT2+dtzpLuUlaskldJn0hCGnZK9gI4xm26o0Aq7BoMSO+T1/gJJUj1iUMRLBAL4fV4LlpozSC/zO3lnTHPVgJH+mUdLxTasfuigE42gSLKjsHxuQIjISHoW5xnaIcpjfMnQftnmQBSPqW7+/xyoMqsYP/A9/7sX01FI5jH+44zvARpjLXg73jtmBU4z/Kmyt3hQVlxZBtpxSRZI4xmbSAzhRA4papyyCQws4Ws7eAULZKjIccdS6wYCnktBBrfbUBQfJGYbYXDLCmjK2L9wKP1NBpwk0U1nCwUvEeFWeoYpqF8lO6cHZL7eazI2Tn7s3XDLeYN1jEG5lBp3gLtWBncXDx/hOkEVWxlEQBs+wR9VbRxdW2BdHoMsGC/BZ19KWjgqBX4Q8xVZsYZ94YovAZl1jkkdK6cF5Q1U4Lxdpc+b1rGCPRp7DZEV9uPgMQlBwbjy1Aavz3JzzNki/4hTH3kJ8=
  file: 
    - "build/SpaceInvadersRemake-osx.app"
    - "build/SpaceInvadersRemake-win.exe"
  skip_cleanup: true
  on:
	tags: true
