language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- chmod 777 ./tools/install-unity.sh
- ./tools/install-unity.sh
script:
- cd tools
- chmod 777 ./buildOSX.sh
- ./buildOSX.sh
- chmod 777 ./buildWIN.sh
- ./buildWIN.sh