language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- chmod 777 ./tools/install-unity.sh
- ./tools/install-unity.sh
script:
- cd tools
- chmod 777 ./buildOSX.sh
- ./buildOSX.sh
- cat buildOSX.log
- chmod 777 ./buildWIN.sh
- ./buildWIN.sh

notifications:
  slack: skahal:FAEM5y78ET68PglHiZXXRVqh

deploy:
  provider: releases
  api_key:
    secure: St9u32gh53SKSxM09xgwexOXNWStu4maYA2LlwrqnCaWh2N7X00h0bgX0MQT2URjPUcRmY6yv3pHYof43XImYzL0tuv8jsMCSJMS7DpG0qyVrXYGbYpvGGluiBkjiQctr63exMZNiAurqLaSKj/jUyDny97BcVXYzUkGEXA+3RAb6o5xLXon8PadCtT1rJHEShV+CQX0tshXKhFcE01ZdYgkg9iTDOUwhUmxwZdAvDOrpZa+qqzq2hJK4FiOencvalqAlG1uJhXipVB9LmtHpDA1U2b44OWlFUZQ8mWw58biuPHJDqRLjtb1EQr+XrJ5j9xmopmIc8loKvt2qPsVtJlnLBUQ7dez3X+x4Xnu858l7zmXfKe5SSp7TRiQ1SSEEyV/rA0QPI75Bf1arO7a3O5P2yORpT+6rb0uJyVHqUQpbYcYVPHMpcNpliQ4gbv1vjkA5OoHwpp+Dc8EEGtK/hUH4wOZtR/CcuYCp5r6rLQ07oieQ/SgR4UWs1+X+ZMoKnKnhTnIZQazorDIoPehuW46jAZjv7RfoZvn45wjX0TP/lBYeZ7Md3sVfTS5diZwkff8dJviCvVeQszHXtLCBbxyCSYej0eeDcautBzbCuwvsgzm8B2cvIxEq+Z2CG28xq41/znnQGzYdtmjeRIGurck9ITYgCVGGMKK6lFq5qo=
  file: build/SpaceInvadersRemake-osx.app
  on:
    repo: skahal/SpaceInvadersRemake
